var fName = "Khurram";
console.log("Is fName == 'Khurram' ? I predict true.");
console.log(fName == "Khurram");
console.log("Is fName == 'Bilal'? I predict false");
console.log(fName == "Bilal");
var lName = "Raza";
console.log("Is lName == 'Raza'? I predict true.");
console.log(lName == "Raza");
console.log("Is lName == 'khurshid'? I predict false.");
console.log(lName == "khurshid");
var lang = "English";
console.log("Is lang == 'English' ? I predict true.");
console.log(lang == "English");
console.log("Is lang == 'Urdu'? I predict false.");
console.log(fName == "Urdu");
var book = "Fatawa";
console.log("Is book == 'fatawa'? I predict true.");
console.log(book == "Fatawa");
console.log("Is book == 'Nahaw'? I predict false.");
console.log(book == "Nahaw");
var teacher = "Sir kashif";
console.log("Is teacher == 'Sir kashif'? I predict true.");
console.log(teacher == "Sir kashif");
console.log("Is teacher == 'Sir sikandar'? I predict false.");
console.log(teacher == "Sir sikandar");
